// English language pack
window.I18N_EN = {
    // Sidebar
    "sidebar.system": "Server System",
    "sidebar.server_monitor": "Server Monitor",
    "sidebar.dashboard": "Dashboard",
    "sidebar.host_management": "Host Management",
    "sidebar.history": "History Records",
    "sidebar.settings": "System Settings",
    
    // Host Management Page
    "host_management.title": "🖥️ Host Management",
    "host_management.subtitle": "Add and manage monitored servers",
    "host_management.add_host": "Add Host",
    "host_management.ip_address": "IP Address",
    "host_management.ip_placeholder": "e.g., 192.168.80.131",
    "host_management.username": "Username",
    "host_management.username_placeholder": "e.g., root",
    "host_management.password": "Password",
    "host_management.password_placeholder": "Enter SSH password",
    "host_management.ssh_port": "SSH Port (default 22)",
    "host_management.add_host_btn": "Add Host",
    "host_management.host_list": "Host List",
    "host_management.refresh_data": "Refresh Data",
    "host_management.refreshing": "Refreshing...",
    "host_management.no_hosts": "No hosts added yet, please click 'Add Host' above",
    "host_management.loading": "Loading...",
    "host_management.delete": "Delete",
    "host_management.delete_confirm": "Are you sure to delete host {ip}?",
    "host_management.delete_success": "✅ Host {ip} deleted successfully!",
    "host_management.add_success": "✅ Host {ip} added successfully!",
    
    // Table Columns
    "table.ip": "IP Address",
    "table.username": "Username",
    "table.ssh_port": "SSH Port",
    "table.cpu_usage": "CPU Usage",
    "table.memory_usage": "Memory Usage",
    "table.disk_usage": "Disk Usage",
    "table.operations": "Operations",
    "table.status": "Status",
    "table.record_time": "Record Time",
    
    // Status
    "status.online": "Online",
    "status.offline": "Offline",
    
    // Messages
    "message.success": "Success",
    "message.error": "Error",
    "message.warning": "Warning",
    "message.info": "Info",
    "message.load_failed": "Load failed",
    "message.add_failed": "Add failed",
    "message.delete_failed": "Delete failed",
    "message.invalid_ip": "Please enter a valid IP address!",
    "message.empty_username": "Username cannot be empty!",
    "message.empty_password": "Password cannot be empty!",
    "message.invalid_port": "Please enter a valid port number (1-65535)!",
    
    // Dashboard
    "dashboard.title": "📊 Dashboard",
    "dashboard.subtitle": "Real-time monitoring of all servers",
    "dashboard.total_servers": "Total Servers",
    "dashboard.running_normal": "Running Normal",
    "dashboard.avg_cpu_usage": "Average CPU Usage",
    "dashboard.cpu_trend": "CPU Usage Trend",
    "dashboard.memory_trend": "Memory Usage Trend",
    "dashboard.server_status": "Server Detailed Status",
    "dashboard.unit_servers": "units",
    "dashboard.total_servers_desc": "Total number of added servers",
    "dashboard.running_normal_desc": "Servers with normal SSH connection",
    "dashboard.avg_cpu_usage_desc": "Average CPU load of all servers",
    
    // History Records
    "history.title": "📊 History Records",
    "history.subtitle": "View and export server monitoring history data",
    "history.query_conditions": "Query Conditions",
    "history.host_ip": "Host IP",
    "history.all_hosts": "All Hosts",
    "history.time_range": "Time Range",
    "history.last_1h": "Last 1 Hour",
    "history.last_6h": "Last 6 Hours",
    "history.last_12h": "Last 12 Hours",
    "history.last_24h": "Last 24 Hours",
    "history.custom": "Custom",
    "history.start_time": "Start Time",
    "history.end_time": "End Time",
    "history.query": "Query",
    "history.export_csv": "Export CSV",
    "history.data_list": "History Data List",
    "history.no_data": "No matching historical data",
    "history.export_success": "Export successful, downloading...",
    "history.custom_time_required": "Please select custom time range",
    
    // System Settings
    "settings.title": "⚙️ System Settings",
    "settings.subtitle": "Configure system parameters and monitoring options",
    "settings.monitor_config": "Monitor Configuration",
    "settings.refresh_interval": "Auto Refresh Interval (seconds)",
    "settings.cpu_threshold": "CPU Alert Threshold (%)",
    "settings.memory_threshold": "Memory Alert Threshold (%)",
    "settings.system_params": "System Parameters",
    "settings.theme_switch": "Theme Switch",
    "settings.dark_theme": "Dark Theme (Default)",
    "settings.light_theme": "Light Theme",
    "settings.data_retention": "Data Retention Days",
    "settings.save_settings": "Save Settings",
    "settings.save_success": "✅ Save successful!",
    "settings.unit_seconds": "seconds",
    "settings.7_days": "7 days (default)",
    "settings.15_days": "15 days",
    "settings.30_days": "30 days"
};