// 中文语言包
window.I18N_ZH = {
    // 侧边栏
    "sidebar.system": "服务器系统",
    "sidebar.server_monitor": "服务器监控",
    "sidebar.dashboard": "监控大屏",
    "sidebar.host_management": "主机管理",
    "sidebar.history": "历史记录",
    "sidebar.settings": "系统设置",
    
    // 主机管理页面
    "host_management.title": "🖥️ 主机管理",
    "host_management.subtitle": "添加和管理监控的服务器",
    "host_management.add_host": "添加主机",
    "host_management.ip_address": "IP 地址",
    "host_management.ip_placeholder": "例如: 192.168.80.131",
    "host_management.username": "用户名",
    "host_management.username_placeholder": "例如: root",
    "host_management.password": "密码",
    "host_management.password_placeholder": "请输入SSH密码",
    "host_management.ssh_port": "SSH端口（默认22）",
    "host_management.add_host_btn": "添加主机",
    "host_management.host_list": "主机列表",
    "host_management.refresh_data": "刷新数据",
    "host_management.refreshing": "刷新中...",
    "host_management.no_hosts": "暂无已添加的主机，请点击上方「添加主机」按钮",
    "host_management.loading": "加载中...",
    "host_management.delete": "删除",
    "host_management.delete_confirm": "确定要删除主机 {ip} 吗？",
    "host_management.delete_success": "✅ 主机 {ip} 删除成功！",
    "host_management.add_success": "✅ 主机 {ip} 添加成功！",
    
    // 表格列名
    "table.ip": "IP地址",
    "table.username": "用户名",
    "table.ssh_port": "SSH端口",
    "table.cpu_usage": "CPU使用率",
    "table.memory_usage": "内存使用率",
    "table.disk_usage": "磁盘使用率",
    "table.operations": "操作",
    "table.status": "状态",
    "table.record_time": "记录时间",
    
    // 状态
    "status.online": "在线",
    "status.offline": "离线",
    
    // 消息提示
    "message.success": "成功",
    "message.error": "错误",
    "message.warning": "警告",
    "message.info": "信息",
    "message.load_failed": "加载失败",
    "message.add_failed": "添加失败",
    "message.delete_failed": "删除失败",
    "message.invalid_ip": "请输入合法的IP地址！",
    "message.empty_username": "用户名不能为空！",
    "message.empty_password": "密码不能为空！",
    "message.invalid_port": "请输入合法的端口号（1-65535）！",
    
    // 监控大屏
    "dashboard.title": "📊 监控大屏",
    "dashboard.subtitle": "实时监控所有服务器状态",
    "dashboard.total_servers": "总服务器数",
    "dashboard.running_normal": "正常运行",
    "dashboard.avg_cpu_usage": "平均CPU使用率",
    "dashboard.cpu_trend": "CPU使用率趋势",
    "dashboard.memory_trend": "内存使用率趋势",
    "dashboard.server_status": "服务器详细状态",
    "dashboard.unit_servers": "台",
    "dashboard.total_servers_desc": "已添加的服务器总数",
    "dashboard.running_normal_desc": "SSH连接正常的服务器",
    "dashboard.avg_cpu_usage_desc": "所有服务器CPU平均负载",
    
    // 历史记录
    "history.title": "📊 历史记录",
    "history.subtitle": "查看和导出服务器监控历史数据",
    "history.query_conditions": "查询条件",
    "history.host_ip": "主机IP",
    "history.all_hosts": "所有主机",
    "history.time_range": "时间范围",
    "history.last_1h": "近1小时",
    "history.last_6h": "近6小时",
    "history.last_12h": "近12小时",
    "history.last_24h": "近24小时",
    "history.custom": "自定义",
    "history.start_time": "开始时间",
    "history.end_time": "结束时间",
    "history.query": "查询",
    "history.export_csv": "导出CSV",
    "history.data_list": "历史数据列表",
    "history.no_data": "暂无匹配的历史数据",
    "history.export_success": "导出成功，正在下载...",
    "history.custom_time_required": "请选择自定义时间范围",
    
    // 系统设置
    "settings.title": "⚙️ 系统设置",
    "settings.subtitle": "配置系统参数和监控选项",
    "settings.monitor_config": "监控配置",
    "settings.refresh_interval": "自动刷新频率（秒）",
    "settings.cpu_threshold": "CPU告警阈值（%）",
    "settings.memory_threshold": "内存告警阈值（%）",
    "settings.system_params": "系统参数",
    "settings.theme_switch": "主题切换",
    "settings.dark_theme": "深色主题（默认）",
    "settings.light_theme": "浅色主题",
    "settings.data_retention": "数据保留天数",
    "settings.save_settings": "保存设置",
    "settings.save_success": "✅ 保存成功！",
    "settings.unit_seconds": "秒",
    "settings.7_days": "7天（默认）",
    "settings.15_days": "15天",
    "settings.30_days": "30天"
};